### ISSUE TITLE
The baseline code

### ISSUE THREAD

**Issue by PipiZong** [linjieli222/HERO#15]
Hi,

Could you please also share the baseline codes of F-TRM and H-TRM? That would be helpful. Thanks!

**Comment by linjieli222** [comment]
Hi, 

Thank you for your interests in this project. We do not have a plan to release the baseline code due to other project priorities. However, I believe it will not take too much work to modify our released code to get the baseline model. The details of the baseline models are described in Sec. 4.3 and the corresponding footnotes of our paper. 

If you have any questions about the baseline model implementations, please share your questions here. Thanks.

**Comment by linjieli222** [comment]
Closed due to inactivity.
