### ISSUE TITLE
download HowTo100M dataset

### ISSUE THREAD

**Issue by JKBox** [linjieli222/HERO#24]
As offered in official website, the feature dataset link seems down, how to download the feature dataset? or raw video dataset?
https://www.rocq.inria.fr/cluster-willow/amiech/howto100m/s3d_features_readme.txt

**Comment by linjieli222** [comment]
@JKBox 

Thanks for your interest in our project and sorry for the late reply.

Due to copyright issue, we could not redistribute the raw videos. Please contact the original authors of HowTo100M for instructions to obtain a copy. 

For HowTo100M features used in HERO pre-training, we did not provide a direct download link due to its large size. Our data hosting service currently does not support downloading of such large files. If you wish to get a copy of our features, please send me an email, so we can figure out a plan.

Thanks.

**Comment by linjieli222** [comment]
Closed due to inactivity.
